### ISSUE TITLE
Add original AROMA code

### ISSUE THREAD

**Issue by tsalo** [Brainhack-Donostia/ica-aroma-org#1]
The initial version of this repository will be the current version of AROMA.

We should probably include license and attribution information about the code in the README.

**Comment by eurunuela** [comment]
I just created a reminder for this. I will do it first thing tomorrow.

**Comment by tsalo** [comment]
No time pressure. I just want to start creating issues for the things we want to do before the actual event.

**Comment by eurunuela** [comment]
Code's already on the repo 😉
