### ISSUE TITLE
Abstract for BHD 2020

### ISSUE THREAD

**Issue by CesarCaballeroGaudes** [Brainhack-Donostia/ica-aroma-org#16]
Hello, It would be nice to have an abstract of the talk for BHD 2020. Any ideas? @tsalo @eurunuela

**Comment by eurunuela** [comment]
We have some examples on the [Brainhack Donostia website](https://brainhack-donostia.github.io).

**Comment by eurunuela** [comment]
How about something like this?

> In this talk I will show you how you can start and work on a collaborative Python project from scratch using GitHub. With a little help from some colleagues, we will take the ICA-AROMA package, that is used in functional MRI data analysis but is no longer maintained, and make a new version of it that relies 100% on Python. In the process, we will refactor the code from a script into a package, add automatic tests that ensure the correct functionality of the changes we add, drop the FSL dependency, make the algorithm work in the subject space, and probably face a setback or two. In essence, it will be a complete GitHub collaboration experience condensed into a 1h15 tutorial.

**Comment by danalclop** [comment]
Hi there! 👋🏻  I also wrote a short bio for you @tsalo. Feel free to suggest, change, or adapt anything!

> **A bit about Taylor Salo**
> 
> Taylor Salo is a fourth-year doctoral student in the Department of Psychology at Florida International University working with Dr Angela Laird. He maintains NiMARE, a Python package for neuroimaging meta-analyses, and contributes to many other open-source projects such as BIDS (a standard for organizing and describing outputs of neuroimaging experiments), tedana (a library for denoising multi-echo fMRI data), and the physiopy suite (a set of tools to operate physiological files in MRI setups), among others.
> 
> If you’re interested in getting to know Taylor better, have a look at [his GitHub README](https://github.com/tsalo).

**Comment by tsalo** [comment]
@eurunuela The abstract looks awesome!

@danalclop that looks great, thank you! Just one minor change- I'm a sixth year grad student at this point. I think I need to update my various profiles to reflect that.

**Comment by danalclop** [comment]
Great, thanks a lot @tsalo! One last request: Can you send me a profile picture with good resolution so I can make one of these [cool cards](https://twitter.com/BHDonostia/status/1321474736010989568/photo/1) for you?

**Comment by tsalo** [comment]
Sure, here's one.
[salo_photo](https://user-images.githubusercontent.com/8228902/98130182-fb45b580-1e87-11eb-8aca-3276e1fa8287.png)

**Comment by eurunuela** [comment]
Closing this. Thank you @tsalo and @danalclop ! 🎉
