### ISSUE TITLE
Make inFeat and inFile arguments mutually exclusive

### ISSUE THREAD

**Issue by tsalo** [Brainhack-Donostia/ica-aroma-org#17]
This is a very simple change to the argument parser.

**Comment by tsalo** [comment]
It turns out that, since the `inFile` argument comes with a whole group of parameters, this may not be possible. We need to choose between having two groups of arguments (FEAT vs. individual files) that are _not_ mutually exclusive (at least in the parser) and having two mutually exclusive arguments (inFeat and inFile) with a set of unrelated arguments (i.e., not setting the arguments that are only valid when inFile is provided as a group with inFile). I'm not sure which is more readable.

**Comment by eurunuela** [comment]
If I understood correctly, the second option sounds more strict. In that case, I'd lean towards the second option as we'd be forcing the users to provide the arguments correctly.

**Comment by tsalo** [comment]
Okay, that works. I'll implement that and open a PR soon. The additional logic, where the other arguments require `inFile`, will get documented in their help strings and actually enforced in the main function, rather than the parser.
