### ISSUE TITLE
Outline for the tutorial

### ISSUE THREAD

**Issue by eurunuela** [Brainhack-Donostia/ica-aroma-org#31]
This is a possible outline for the tutorial and a rough estimate of the time needed for each step (take into account the session will be 1h15 long):

- The original ICA-AROMA repository: what it does, what we want to achieve (5 minutes).
- How to open an empty repository on GitHub, forking and cloning (10 minutes).
- Creating a branch, taking the necessary parts of the original workflow, and pushing (10 minutes).
- Checking the GitHub notifications: "oh! someone opened an issue to add automatic testing!". Asking for a PR in the issue and reviewing the PR (10 minutes).
- Show how CircleCI is set up (5 minutes).
- Let's open an issue now to say we need to refactor the code. Open the PR (we have the code ready) and wait for someone to review it (10 minutes).
- PR for dropping the FSL dependency (5 minutes).
- Native space PR (5 minutes).

This would make a total of 60 minutes and would give us 15 extra for people to ask. I think we should address questions from participants on each of the points above or else they may get lost.

I did not add the merging conflicts because I'd like to know where you think they'd be the easiest to have @tsalo .

**Comment by tsalo** [comment]
1. What is ICA-AROMA? Why do we want it?
1. Create a repository (`Brainhack-Donostia/aroma`).
    1. Eneko will transfer issues one-by-one from this repo to the new one.
1. Create a branch for changes.
1. Propagate current version repo to new branch, minus all tests and test config.
1. Open a pull request to `main`.
1. Eneko will fork to his account.
1. Eneko will open an issue about testing.
1. Eneko will open a PR with tests we didn't copy over.
1. Eneko will go to CircleCI to set it up.
1. Review and merge PR.
1. I will open a PR to add CodeCov and CircleCI badges to the README.
1. I will copy over pandas-related changes from #46 to my fork and open a PR.
1. Eneko will review the pandas PR.

**Comment by eurunuela** [comment]
That was fun. Thank you for taking part @tsalo !
