### ISSUE TITLE
Reorganize into Python package

### ISSUE THREAD

**Issue by tsalo** [Brainhack-Donostia/ica-aroma-org#4]
Instead of two files, we should have a proper Python package. We can model the package setup after a package most of the devs are familiar with (e.g., `tedana` or `phys2bids`), _or_ we could use a template package like `effigies/cookiecutter-packaging`.

**Comment by CesarCaballeroGaudes** [comment]
My vote would be to follow tedana because it is a software that this repo could be integrated to

**Comment by eurunuela** [comment]
I'd stick to the setup we already know; i.e. `tedana` or `phys2bids` .
