### ISSUE TITLE
Add unit testing and continuous integration

### ISSUE THREAD

**Issue by tsalo** [Brainhack-Donostia/ica-aroma-org#5]
There are currently no tests in the ICA-AROMA code. We can add unit tests and continuous integration with CircleCI to ensure that we don't introduce any breaking changes. The good news is that, since we're working off of functional code, we can run ICA-AROMA on a test dataset to generate outputs, and then compare against those as our "ground truth."

**Comment by eurunuela** [comment]
Do we want to write an integration test with the original code?

I'm thinking it might be best to do the refactoring making sure the integration test passes on every refactoring PR.

**Comment by tsalo** [comment]
@eurunuela I know that you have added hardcoded values to the tests, but what do you think about adding actual outputs from `ICA-AROMA` (the original version)?

**Comment by eurunuela** [comment]
Sure! That sounds great! I added hardcoded values mainly for the refactoring.

I'll have a look at the Makefile, thanks!

**Comment by eurunuela** [comment]
The Makefile was fine. I had to add a couple of options to `setup.cfg`. I've made them in #18
